### ISSUE TITLE
dúvida: produção

### ISSUE THREAD

**Issue by EvertonSA** [bancodobrasil/api-mtls-ambassador-gateway#1]
já está em produção? 

queremos utilizar para a api pix cob

**Comment by tiagostutz** [comment]
Oi @EvertonSA ! Tudo beleza?

Você diz a API PIX COB? Se ela está em Produção já?

**Comment by EvertonSA** [comment]
eu já uso a API PIX COB, ela está em produção @tiagostutz. o que eu quero é fechar mtls com o banco do brasil. é um requisito mandatário pelo BACEN, e no forum do bb só responderam que não tem MTLS e não tem previsão

**Comment by EvertonSA** [comment]
usamos ambassador em produção aqui também @tiagostutz, vcs não querem fechar com a gente? primeira integração mtls do bb?

**Comment by EvertonSA** [comment]
https://forum.developers.bb.com.br/t/conexao-mtls-e-headers-customizados/2683/10 uma baita demora pra entregar o webhook e o mtls

**Comment by tiagostutz** [comment]
Salve @EvertonSA!! Desculpe a demora.
Então, a gente tá no meio da implantação do Webhook do PIX/Cobrança/Arrecadação com PIX, por isso não consigo tocara agora essa frente do mTLS para os requests. Mas se vocês quiserem implantar o Webhook com mTLS, posso colocá-los no piloto aqui e a gente toca em frente... o que acha?

**Comment by EvertonSA** [comment]
queremos sim, já temos webhook mtls com varios psp's! queremos muito estar na frente desse piloto mestre!

**Comment by tiagostutz** [comment]
Show.!
Te mandei uma mensagem no LinkedIn com meu contato pra caminharmos com essa frente.! Daí pego contigo os dados certinho pra colocarmos vocês no piloto. Vai ser show.!
